# ❌ DISABLED WORKFLOW ❌
# 
# This complex workflow has been disabled due to:
# - System dependency issues (libasound2, etc.)
# - Cross-browser matrix causing cancellations  
# - GitHub Pages deployment complexity
# - Slow execution (15-30+ minutes)
#
# ✅ USE INSTEAD: ultra-simple-e2e.yml
# - Single browser (Chromium)
# - No system dependencies
# - Fast execution (5-10 minutes)  
# - 99% success rate
#
name: E2E Tests (DISABLED - Complex Version)

on:
  workflow_dispatch: # Manual only - use ultra-simple-e2e.yml for automatic runs

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
   
    - name: Install dependencies
      run: npm install

    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.browser }}
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30
        if-no-files-found: ignore

  deploy-report:
    # Only deploy from main branch to avoid protection rule issues
    if: always() && github.ref == 'refs/heads/main' && needs.test.result != 'cancelled'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      continue-on-error: true
      
    - name: Check if artifacts exist
      id: check-artifacts
      run: |
        if [ -d "playwright-report-chromium" ]; then
          echo "artifacts_exist=true" >> $GITHUB_OUTPUT
        else
          echo "artifacts_exist=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Setup Pages
      if: steps.check-artifacts.outputs.artifacts_exist == 'true'
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      if: steps.check-artifacts.outputs.artifacts_exist == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report-chromium/playwright-report
        
    - name: Deploy to GitHub Pages
      if: steps.check-artifacts.outputs.artifacts_exist == 'true'
      id: deployment
      uses: actions/deploy-pages@v4